[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">=3.9"
dependencies = ["pandas", "numpy"]

[project.optional-dependencies]
dev = ["pytest"]

[tool.setuptools]
packages = ["goat"]