[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "goat"
version = "0.0.1a0"
requires-python = ">=3.9"

dependencies = [
    "pandas",
    "numpy",
    "matplotlib",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "pytest-describe",
    "ruff",
]

[tool.setuptools]
packages = ["goat"]