[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[project]
name = "goat"
version = "0.0.2a0"
requires-python = ">=3.13"
description = "A simple, fast, and flexible trader program."

dependencies = [
    "numpy>=2.4.0",
    "polars",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.12.0",
    "structlog>=25.5.0",
]

[dependency-groups]
dev = [
    "bandit",
    "coverage",
    "docstr-coverage",
    "nox",
    "pre-commit",
    "pytest",
    "pytest-cov",
    "pytest-describe",
    "pytest-env",
    "pytest-xdist",
    "pyupgrade",
    "radon",
    "ruff",
    "uv",
    "ty",
]

[tool.uv.build-backend]
packages = ["goat"]

[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py314"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]
ignore = []

[tool.ruff.lint.isort]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ty.environment]
python = ".venv"

[tool.coverage.run]
source = ["goat"]
branch = true

[tool.coverage.report]
fail_under = 60 # increase to 80 when ready
show_missing = true
exclude_lines = [
    "pragma: no cover",
    "if TYPE_CHECKING:",
]