name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.13", "3.14"]

    steps:
    - uses: actions/checkout@v6
